### ISSUE TITLE
[Question]: Cannot connect from SQL Server Management Studio

### ISSUE THREAD

**Issue by kewinbrand** [babelfish-for-postgresql/babelfish_extensions#55]
### Contact Details

kewin.robetti@korp.com.br

### What's the question?

When connecting to the cluster via nssm  it shows the following error

```
===================================
Cannot connect to 192.168.1.18.
===================================
Specified cast is not valid. (Microsoft.SqlServer.ConnectionInfo)
------------------------------
Program Location:
 at Microsoft.SqlServer.Management.Common.ServerConnection.get_FixedServerRoles()
at Microsoft.SqlServer.Management.SqlStudio.Explorer.ObjectExplorerService.CheckAndEnableSmoXps(SqlConnection connection, Boolean smoXpsEnabled)
at Microsoft.SqlServer.Management.SqlStudio.Explorer.ObjectExplorerService.CheckDacAndSmo(SqlConnection sqlConnection)
at Microsoft.SqlServer.Management.SqlStudio.Explorer.ObjectExplorerService.ValidateConnection(UIConnectionInfo ci, IServerType server)
at Microsoft.SqlServer.Management.UI.ConnectionDlg.Connector.ConnectionThreadUser()
```

### Relevant log output or information

```shell
2021-12-28 22:46:56.502 UTC [190] LOG: message_type: TDS7 Prelogin Message2021-12-28 22:46:56.502 UTC [190] CONTEXT: TDS Protocol: Message Type: TDS Pre-Login, Phase: Login.2021-12-28 22:46:56.515 UTC [190] LOG: message_type: TDS7 Login2021-12-28 22:46:56.515 UTC [190] CONTEXT: TDS Protocol: Message Type: TDS Login7, Phase: Login.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 3manuek** [comment]
Hi @kewinbrand, 
Currently, the ability to connect from the SSMS Object Explorer is not supported. Please refer to the documentation here on how you can connect. https://babelfishpg.org/docs/usage/command-line/#using-ssms-to-connect.

**Comment by max-webster** [comment]
Since this is a known and documented limitation, I'll close the question.
